"""Add Configuration table

Revision ID: 682610a89752
Revises: de3dd19ecb74
Create Date: 2025-08-15 08:59:54.781652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682610a89752'
down_revision = 'de3dd19ecb74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configurations')
    # ### end Alembic commands ###
